/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourseOfferingManagerPanel.java
 *
 * Created on Apr 24, 2011, 7:54:01 PM
 */

package KnightRMS;

import KnightEDU.Class;
import KnightEDU.Section;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import knightrms.SectionFinderGUI;

/**
 *
 * @author Alexander Darino
 */
public class CourseOfferingManagerPanel extends javax.swing.JPanel {


    private KnightEDU.DBMS.SQL.DB db;
    private KnightEDU.Course.Offering courseOffering;

    public CourseOfferingManagerPanel(KnightEDU.DBMS.SQL.DB db)
    {
        this();
        this.db = db;
    }

    /** Creates new form CourseOfferingManagerPanel */
    private CourseOfferingManagerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel16 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CourseIDTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        YearTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TermCB = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PrimaryComponentTypeCB = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        CourseOfferingAddButton = new javax.swing.JButton();
        CourseOfferingRemoveButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComponentList = new javax.swing.JList();
        jPanel12 = new javax.swing.JPanel();
        ComponentTypeCB = new javax.swing.JComboBox();
        ComponentAddButton = new javax.swing.JButton();
        ComponentRemoveButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClassList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        classEditorCourseOfferingLabel = new javax.swing.JLabel();
        classEditorCourseOfferingField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        classEditorClassIDField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        classEditorSectionIDField = new javax.swing.JTextField();
        SectionIDSearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        classEditorSectionNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        ClassAddButton = new javax.swing.JButton();
        ClassRemoveButton = new javax.swing.JButton();

        setMinimumSize(getPreferredSize());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Offerings"));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CourseID:");
        jPanel2.add(jLabel3);

        CourseIDTF.setColumns(8);
        CourseIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseIDTFActionPerformed(evt);
            }
        });
        CourseIDTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CourseIDTFFocusLost(evt);
            }
        });
        jPanel2.add(CourseIDTF);

        jPanel5.add(jPanel2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Year:");
        jPanel3.add(jLabel4);

        YearTF.setColumns(4);
        YearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTFActionPerformed(evt);
            }
        });
        YearTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                YearTFFocusLost(evt);
            }
        });
        jPanel3.add(YearTF);

        jPanel5.add(jPanel3);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Term:");
        jPanel4.add(jLabel5);

        TermCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FALL", "SPRING", "SUMMER" }));
        TermCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TermCBItemStateChanged(evt);
            }
        });
        jPanel4.add(TermCB);

        jPanel5.add(jPanel4);

        jPanel9.add(jPanel5);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Primary Componet Type:");
        jPanel6.add(jLabel6);

        PrimaryComponentTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LECTURE", "LAB", "FIELD", "INDEPENDENT_STUDY" }));
        jPanel6.add(PrimaryComponentTypeCB);

        jPanel8.add(jPanel6);

        CourseOfferingAddButton.setText("Add");
        CourseOfferingAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseOfferingAddButtonActionPerformed(evt);
            }
        });
        jPanel7.add(CourseOfferingAddButton);

        CourseOfferingRemoveButton.setText("Remove");
        CourseOfferingRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseOfferingRemoveButtonActionPerformed(evt);
            }
        });
        jPanel7.add(CourseOfferingRemoveButton);

        jPanel8.add(jPanel7);

        jPanel9.add(jPanel8);

        jPanel16.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Components"));
        jPanel11.setLayout(new java.awt.BorderLayout());

        ComponentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ComponentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ComponentList);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ComponentTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lecture", "Lab", "Field", "Independant Study" }));
        jPanel12.add(ComponentTypeCB);

        ComponentAddButton.setText("Add");
        ComponentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentAddButtonActionPerformed(evt);
            }
        });
        jPanel12.add(ComponentAddButton);

        ComponentRemoveButton.setText("Remove");
        ComponentRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentRemoveButtonActionPerformed(evt);
            }
        });
        jPanel12.add(ComponentRemoveButton);

        jPanel11.add(jPanel12, java.awt.BorderLayout.SOUTH);

        jPanel16.add(jPanel11, java.awt.BorderLayout.CENTER);

        add(jPanel16);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Component Classes"));
        jPanel13.setLayout(new java.awt.BorderLayout());

        ClassList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ClassListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ClassList);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Editor"));
        jPanel1.setMinimumSize(jPanel1.getPreferredSize());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel17.setLayout(new java.awt.GridBagLayout());

        classEditorCourseOfferingLabel.setText("Course Offering:");
        jPanel17.add(classEditorCourseOfferingLabel, new java.awt.GridBagConstraints());

        classEditorCourseOfferingField.setColumns(25);
        classEditorCourseOfferingField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(classEditorCourseOfferingField, gridBagConstraints);

        jLabel2.setText("Class ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel17.add(jLabel2, gridBagConstraints);

        classEditorClassIDField.setColumns(6);
        classEditorClassIDField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(classEditorClassIDField, gridBagConstraints);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Section ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel17.add(jLabel9, gridBagConstraints);

        classEditorSectionIDField.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(classEditorSectionIDField, gridBagConstraints);

        SectionIDSearchButton.setText("Search");
        SectionIDSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionIDSearchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(SectionIDSearchButton, gridBagConstraints);

        jLabel1.setText("Section #:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel17.add(jLabel1, gridBagConstraints);

        classEditorSectionNumberField.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(classEditorSectionNumberField, gridBagConstraints);

        jLabel7.setText("Capacity: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel17.add(jLabel7, gridBagConstraints);

        capacityField.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(capacityField, gridBagConstraints);

        jPanel1.add(jPanel17);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        ClassAddButton.setText("Add");
        ClassAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassAddButtonActionPerformed(evt);
            }
        });
        jPanel15.add(ClassAddButton);

        ClassRemoveButton.setText("Remove");
        ClassRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassRemoveButtonActionPerformed(evt);
            }
        });
        jPanel15.add(ClassRemoveButton);

        jPanel1.add(jPanel15);

        jPanel18.add(jPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel18);
    }// </editor-fold>//GEN-END:initComponents

    private void ClassAddButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ClassAddButtonActionPerformed
    {//GEN-HEADEREND:event_ClassAddButtonActionPerformed
//
//        //Get data from Corys module
//        db.addClass(Integer.parseInt(ClassList.getSelectedValue().toString()), Integer.parseInt(SectionIDTF.getText()), Integer.parseInt(SectionNumTF.getText()), 20, 1);
//
//        //Update the Class List Box with the class added
//        javax.swing.event.ListSelectionEvent evtL = null;
//        ComponentListValueChanged(evtL);
        KnightEDU.Class classObj = db.addClass(Integer.parseInt(classEditorSectionIDField.getText()), Integer.parseInt(classEditorSectionNumberField.getText()), Integer.parseInt(capacityField.getText()), 0);
        assert classObj != null;
        
}//GEN-LAST:event_ClassAddButtonActionPerformed

    private void ClassRemoveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ClassRemoveButtonActionPerformed
    {//GEN-HEADEREND:event_ClassRemoveButtonActionPerformed
        db.removeClass(Integer.parseInt(ClassList.getSelectedValue().toString()));

        //Update the Class List Box with the class added
        javax.swing.event.ListSelectionEvent evtL = null;
        ComponentListValueChanged(evtL);
}//GEN-LAST:event_ClassRemoveButtonActionPerformed

    private void SectionIDSearchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SectionIDSearchButtonActionPerformed
    {//GEN-HEADEREND:event_SectionIDSearchButtonActionPerformed
       KnightEDU.Section section = SectionFinderGUI.showDialog(null, true, db.querySection());
       if (section != null) classEditorSectionIDField.setText(String.valueOf(section.getSectionID()));
}//GEN-LAST:event_SectionIDSearchButtonActionPerformed

    private void ComponentRemoveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ComponentRemoveButtonActionPerformed
    {//GEN-HEADEREND:event_ComponentRemoveButtonActionPerformed

        KnightEDU.Component Component = db.getComponent(Integer.parseInt(ComponentList.getModel().toString()));

        KnightEDU.Course course = db.getCourse(CourseIDTF.getText());
        KnightEDU.CourseID courseID = course.getID();

        KnightEDU.Term term = null;

        db.removeCourseOfferingComponent(courseID, term.valueOf(TermCB.getSelectedItem().toString()), Integer.parseInt(YearTF.getText()), Component.getID());

        //Update the Class List Box with the class removed
        javax.swing.event.ListSelectionEvent evtL = null;
        ComponentListValueChanged(evtL);
}//GEN-LAST:event_ComponentRemoveButtonActionPerformed

    private void ComponentAddButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ComponentAddButtonActionPerformed
    {//GEN-HEADEREND:event_ComponentAddButtonActionPerformed

        KnightEDU.Course course = db.getCourse(CourseIDTF.getText());
        KnightEDU.CourseID courseID = course.getID();

        KnightEDU.Term term = null;
        KnightEDU.Component.Type type = null;
        KnightEDU.Component.Type ComponentType = null;


        //Fix Code
        db.addCourseOfferingComponent(courseID, term, Integer.parseInt(YearTF.getText()), 1);

        //Update the Class List Box with the class added
        javax.swing.event.ListSelectionEvent evtL = null;
        ComponentListValueChanged(evtL);
}//GEN-LAST:event_ComponentAddButtonActionPerformed

    private void ComponentListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ComponentListValueChanged
    {//GEN-HEADEREND:event_ComponentListValueChanged
        int componentID = (Integer)ComponentList.getSelectedValue();


        //Get the set of components from the users courseID term and year
        Set<Integer> classIDs = db.getComponentClassIDs(componentID);
        ClassList.setModel(new DefaultListModel());
        Set<ClassInfo> classes = new HashSet();
        for (int i : classIDs)
        {
            KnightEDU.Class classObj = db.getClass(i);

            assert classObj != null;
            KnightEDU.Section section = db.getSection(classObj.getSectionID());
            classes.add(new ClassInfo(classObj, section));
        }
        ClassList.setListData(classes.toArray());
}//GEN-LAST:event_ComponentListValueChanged

    public void updateComponentsListing()
    {

        //Get the Course ID from the text field
        String CourseID = CourseIDTF.getText();

        //Get the term from the combo box
        KnightEDU.Term Term = KnightEDU.Term.valueOf(TermCB.getSelectedItem().toString());

        //Get the year from the text field
        int Year;
        if (YearTF.getText().isEmpty()) Year = 0;
            else Year = Integer.parseInt(YearTF.getText());

        //Get the set of components from the users courseID term and year
        courseOffering = db.getCourseOffering(CourseID, Term, Year);
        if (courseOffering == null)
        {
            ComponentList.setModel(new DefaultListModel());
            return;
        }

        Set<Integer> qComponent = db.queryComponent().getComponentIDs(courseOffering.getPrimaryComponentID());

        ComponentList.setListData(qComponent.toArray());
        classEditorCourseOfferingField.setText(courseOffering.toString());
    }

    private void CourseOfferingRemoveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CourseOfferingRemoveButtonActionPerformed
    {//GEN-HEADEREND:event_CourseOfferingRemoveButtonActionPerformed

        KnightEDU.Component Component = db.getComponent(Integer.parseInt(ComponentList.getSelectedValue().toString()));

        KnightEDU.Course course = db.getCourse(CourseIDTF.getText());
        KnightEDU.CourseID courseID = course.getID();

        KnightEDU.Term term = null;

        db.removeCourseOffering(courseID, term.valueOf(TermCB.getSelectedItem().toString()), Integer.parseInt(YearTF.getText()));
}//GEN-LAST:event_CourseOfferingRemoveButtonActionPerformed

    private void CourseOfferingAddButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CourseOfferingAddButtonActionPerformed
    {//GEN-HEADEREND:event_CourseOfferingAddButtonActionPerformed

        try
        {
            KnightEDU.Course course = db.getCourse(CourseIDTF.getText());

            KnightEDU.CourseID courseID = course.getID();

            KnightEDU.Term term = null;
            KnightEDU.Component.Type type = null;


            db.addCourseOffering(courseID, term.valueOf(TermCB.getSelectedItem().toString()), Integer.parseInt(YearTF.getText()), type.valueOf(PrimaryComponentTypeCB.getSelectedItem().toString()));

            //Update the Class List Box with the class added
            javax.swing.event.ListSelectionEvent evtL = null;
            ComponentListValueChanged(evtL);
        }
        catch(NullPointerException e)
        {
            System.out.println("Exception Caught!");
            return;
        }
}//GEN-LAST:event_CourseOfferingAddButtonActionPerformed

    private void CourseIDTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CourseIDTFActionPerformed
    {//GEN-HEADEREND:event_CourseIDTFActionPerformed
        updateComponentsListing();
    }//GEN-LAST:event_CourseIDTFActionPerformed

    private void ClassListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ClassListValueChanged
    {//GEN-HEADEREND:event_ClassListValueChanged
        classEditorClassIDField.setText(String.valueOf(((ClassInfo)ClassList.getSelectedValue()).getClassObj().getID()));
        classEditorSectionIDField.setText(String.valueOf(((ClassInfo)ClassList.getSelectedValue()).getSection().getSectionID()));
    }//GEN-LAST:event_ClassListValueChanged

    private void CourseIDTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_CourseIDTFFocusLost
    {//GEN-HEADEREND:event_CourseIDTFFocusLost
        updateComponentsListing();
    }//GEN-LAST:event_CourseIDTFFocusLost

    private void YearTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_YearTFActionPerformed
    {//GEN-HEADEREND:event_YearTFActionPerformed
        updateComponentsListing();
    }//GEN-LAST:event_YearTFActionPerformed

    private void YearTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_YearTFFocusLost
    {//GEN-HEADEREND:event_YearTFFocusLost
        updateComponentsListing();
    }//GEN-LAST:event_YearTFFocusLost

    private void TermCBItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_TermCBItemStateChanged
    {//GEN-HEADEREND:event_TermCBItemStateChanged
        updateComponentsListing();
    }//GEN-LAST:event_TermCBItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClassAddButton;
    private javax.swing.JList ClassList;
    private javax.swing.JButton ClassRemoveButton;
    private javax.swing.JButton ComponentAddButton;
    private javax.swing.JList ComponentList;
    private javax.swing.JButton ComponentRemoveButton;
    private javax.swing.JComboBox ComponentTypeCB;
    private javax.swing.JTextField CourseIDTF;
    private javax.swing.JButton CourseOfferingAddButton;
    private javax.swing.JButton CourseOfferingRemoveButton;
    private javax.swing.JComboBox PrimaryComponentTypeCB;
    private javax.swing.JButton SectionIDSearchButton;
    private javax.swing.JComboBox TermCB;
    private javax.swing.JTextField YearTF;
    private javax.swing.JTextField capacityField;
    private javax.swing.JTextField classEditorClassIDField;
    private javax.swing.JTextField classEditorCourseOfferingField;
    private javax.swing.JLabel classEditorCourseOfferingLabel;
    private javax.swing.JTextField classEditorSectionIDField;
    private javax.swing.JTextField classEditorSectionNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}

class ClassInfo
{
    private KnightEDU.Class classObj;
    private KnightEDU.Section section;

    public ClassInfo(Class classObj, Section section)
    {
        this.classObj = classObj;
        this.section = section;
    }

    public Class getClassObj()
    {
        return classObj;
    }

    public Section getSection()
    {
        return section;
    }

    @Override
    public String toString()
    {
        return "Class " + classObj.getID() + " Section " + section;
    }


}
