/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoursePlannerPanel.java
 *
 * Created on Apr 21, 2011, 4:08:43 PM
 */

package KnightRMS;

import java.awt.Frame;
import java.util.Set;

/**
 *
 * @author Evan
 */
public class CoursePlannerPanel_NEW extends javax.swing.JPanel {

    private KnightEDU.DBMS.SQL.DB db;
    private Frame parent;
    
    public CoursePlannerPanel_NEW(Frame parent, KnightEDU.DBMS.SQL.DB db)
    {
        this();
        this.db = db;
        this.parent = parent;
    }

    /** Creates new form CoursePlannerPanel */
    private CoursePlannerPanel_NEW() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        coursePlannerLeftPan = new javax.swing.JPanel();
        courseInfoTopPan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        coursePrefixLab2 = new javax.swing.JLabel();
        prefixField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        courseNumLab = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        courseSuffixLab = new javax.swing.JLabel();
        suffixField = new javax.swing.JTextField();
        courseNamePan1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        gradePrefPan1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gradePrefBox1 = new javax.swing.JComboBox();
        creditsPan2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        creditsMinLab2 = new javax.swing.JLabel();
        minCreditsField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        creditsMaxLab2 = new javax.swing.JLabel();
        maxCreditsField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        prerequisitesPanel1 = new KnightRMS.PrerequisitesPanel();
        coursePlannerSeparator = new javax.swing.JSeparator();
        coursePlannerRightPan = new javax.swing.JPanel();
        semOfferedPan = new javax.swing.JPanel();
        occasionalBox = new javax.swing.JCheckBox();
        semOfferedSeparator = new javax.swing.JSeparator();
        semOfferedSemPan = new javax.swing.JPanel();
        fallLab = new javax.swing.JLabel();
        fallEvenBox = new javax.swing.JCheckBox();
        fallOddBox = new javax.swing.JCheckBox();
        springLab = new javax.swing.JLabel();
        springEvenBox = new javax.swing.JCheckBox();
        springOddBox = new javax.swing.JCheckBox();
        summerLab = new javax.swing.JLabel();
        summerEvenBox = new javax.swing.JCheckBox();
        summerOddBox = new javax.swing.JCheckBox();
        courseSearchPan = new javax.swing.JPanel();
        courseListScrollPane = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList();
        searchButton = new javax.swing.JButton();
        courseOptionsPan = new javax.swing.JPanel();
        courseOptionsInsidePan = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        coursePlannerLeftPan.setLayout(new javax.swing.BoxLayout(coursePlannerLeftPan, javax.swing.BoxLayout.LINE_AXIS));

        courseInfoTopPan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        courseInfoTopPan.setPreferredSize(courseInfoTopPan.getMinimumSize());
        courseInfoTopPan.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("CourseID"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setPreferredSize(jPanel7.getMinimumSize());
        jPanel7.setLayout(new java.awt.GridBagLayout());

        coursePrefixLab2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        coursePrefixLab2.setText("Prefix: ");
        jPanel7.add(coursePrefixLab2, new java.awt.GridBagConstraints());

        prefixField.setColumns(3);
        prefixField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(prefixField, gridBagConstraints);

        jPanel3.add(jPanel7);

        jPanel8.setPreferredSize(jPanel8.getMinimumSize());
        jPanel8.setLayout(new java.awt.GridBagLayout());

        courseNumLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        courseNumLab.setText(" Number: ");
        jPanel8.add(courseNumLab, new java.awt.GridBagConstraints());

        numberField.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(numberField, gridBagConstraints);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        courseSuffixLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        courseSuffixLab.setText(" Suffix: ");
        jPanel9.add(courseSuffixLab, new java.awt.GridBagConstraints());

        suffixField.setColumns(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel9.add(suffixField, gridBagConstraints);

        jPanel3.add(jPanel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel3.setText("Name:");
        courseNamePan1.add(jLabel3);

        nameField.setColumns(20);
        courseNamePan1.add(nameField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(courseNamePan1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Grade Type:");
        gradePrefPan1.add(jLabel5);

        gradePrefBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Letter", "S / U" }));
        gradePrefBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradePrefBox1ActionPerformed(evt);
            }
        });
        gradePrefPan1.add(gradePrefBox1);

        jPanel1.add(gradePrefPan1, new java.awt.GridBagConstraints());

        creditsPan2.setBorder(javax.swing.BorderFactory.createTitledBorder("Credits"));
        creditsPan2.setLayout(new java.awt.GridBagLayout());

        creditsMinLab2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        creditsMinLab2.setText("Min: ");
        jPanel5.add(creditsMinLab2);

        minCreditsField.setColumns(2);
        jPanel5.add(minCreditsField);

        creditsPan2.add(jPanel5, new java.awt.GridBagConstraints());

        creditsMaxLab2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        creditsMaxLab2.setText("Max: ");
        jPanel6.add(creditsMaxLab2);

        maxCreditsField.setColumns(2);
        jPanel6.add(maxCreditsField);

        creditsPan2.add(jPanel6, new java.awt.GridBagConstraints());

        jPanel1.add(creditsPan2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jPanel1, gridBagConstraints);

        courseInfoTopPan.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBar(null);

        descriptionArea.setColumns(10000);
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        jScrollPane2.setViewportView(descriptionArea);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        courseInfoTopPan.add(jPanel4, java.awt.BorderLayout.CENTER);

        coursePlannerLeftPan.add(courseInfoTopPan);
        coursePlannerLeftPan.add(prerequisitesPanel1);

        add(coursePlannerLeftPan);

        coursePlannerSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(coursePlannerSeparator);

        coursePlannerRightPan.setLayout(new java.awt.BorderLayout());

        semOfferedPan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semesters Offered", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        semOfferedPan.setLayout(new javax.swing.BoxLayout(semOfferedPan, javax.swing.BoxLayout.LINE_AXIS));

        occasionalBox.setText("Occasional");
        occasionalBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        occasionalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occasionalBoxActionPerformed(evt);
            }
        });
        semOfferedPan.add(occasionalBox);

        semOfferedSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        semOfferedPan.add(semOfferedSeparator);

        semOfferedSemPan.setLayout(new java.awt.GridLayout(3, 3, 40, 20));

        fallLab.setText("     Fall:");
        semOfferedSemPan.add(fallLab);

        fallEvenBox.setText("Even");
        fallEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(fallEvenBox);

        fallOddBox.setText("Odd");
        fallOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fallOddBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fallOddBoxActionPerformed(evt);
            }
        });
        semOfferedSemPan.add(fallOddBox);

        springLab.setText("     Spring:");
        semOfferedSemPan.add(springLab);

        springEvenBox.setText("Even");
        springEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        springEvenBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                springEvenBoxActionPerformed(evt);
            }
        });
        semOfferedSemPan.add(springEvenBox);

        springOddBox.setText("Odd");
        springOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(springOddBox);

        summerLab.setText("     Summer:");
        semOfferedSemPan.add(summerLab);

        summerEvenBox.setText("Even");
        summerEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(summerEvenBox);

        summerOddBox.setText("Odd");
        summerOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(summerOddBox);

        semOfferedPan.add(semOfferedSemPan);

        coursePlannerRightPan.add(semOfferedPan, java.awt.BorderLayout.NORTH);

        courseSearchPan.setLayout(new java.awt.BorderLayout());

        courseList.setBackground(new java.awt.Color(204, 255, 255));
        courseListScrollPane.setViewportView(courseList);

        courseSearchPan.add(courseListScrollPane, java.awt.BorderLayout.CENTER);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        courseSearchPan.add(searchButton, java.awt.BorderLayout.SOUTH);

        courseOptionsPan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        courseOptionsPan.setLayout(new java.awt.GridLayout(1, 0));

        courseOptionsInsidePan.setLayout(new java.awt.GridLayout(1, 2));

        saveButton.setText("Save Course");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        courseOptionsInsidePan.add(saveButton);

        removeButton.setText("Remove Course");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        courseOptionsInsidePan.add(removeButton);

        courseOptionsPan.add(courseOptionsInsidePan);

        courseSearchPan.add(courseOptionsPan, java.awt.BorderLayout.SOUTH);

        coursePlannerRightPan.add(courseSearchPan, java.awt.BorderLayout.CENTER);

        add(coursePlannerRightPan);
    }// </editor-fold>//GEN-END:initComponents

    private void occasionalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occasionalBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_occasionalBoxActionPerformed

    private void fallOddBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fallOddBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fallOddBoxActionPerformed

    private void springEvenBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_springEvenBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_springEvenBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
//                    // If course is in database, update course.
//            if (db.containsCourse(courseID))
//            {
//                KnightEDU.Course c = db.getCourse(courseID);
//                Credits credits = null;
//                c.setName(name);
//                c.setDescription(description);
//                if(minCreditsField == null && maxCreditsField == null)
//                    JOptionPane.showMessageDialog(KnightRMSGUI.this, "Please enter min and/or max credits.");
//                else if(minCreditsField != null && maxCreditsField != null)
//                {
//                    int min = Integer.parseInt(minCreditsField.getText());
//                    int max = Integer.parseInt(maxCreditsField.getText());
//                    credits = Credits.createCredits(min, max);
//                }
//                else if(minCreditsField == null)
//                {
//                    int cMax = Integer.parseInt(maxCreditsField.getText());
//                    credits = Credits.createCredits(cMax);
//                }
//                else
//                {
//                    int cMin = Integer.parseInt(minCreditsField.getText());
//                    credits = Credits.createCredits(cMin);
//                }
//                c.setCredits(credits);
//                c.setGradeType((Type)gradePrefBox.getSelectedItem());
//            }
//
//            // Need a pop-up window here - if the user makes a typo in the course name,
//            // we don't want it to add a new course. Popup window should say something like,
//            // "Course not found in database. Add course to database?" and then have buttons
//            // for yes or no.
//
//            // If course is not in database, add new course.
//            else
//            {
//                Credits credits = null;
//                if(minCreditsField == null && maxCreditsField == null)
//                    JOptionPane.showMessageDialog(KnightRMSGUI.this, "Please enter min and/or max credits.");
//                else if(minCreditsField != null && maxCreditsField != null)
//                {
//                    int min = Integer.parseInt(minCreditsField.getText());
//                    int max = Integer.parseInt(maxCreditsField.getText());
//                    credits = Credits.createCredits(min, max);
//                }
//                else if(minCreditsField == null){
//                    int c = Integer.parseInt(maxCreditsField.getText());
//                    credits = Credits.createCredits(c);
//                }
//                else {
//                    int c = Integer.parseInt(minCreditsField.getText());
//                    credits = Credits.createCredits(c);
//                }
//
//
//                Grade.Type type = (Type)gradePrefBox.getSelectedItem();
//                //db.addCourse(String courseID, String name, String description, Credits credits, Grade.Type gradeType);
//                db.addCourse(courseID, name, description, credits, type);
//            }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
//            if (courseList.getSelectedValue() != null)
//            {
//                db.removeCourse(courseID);
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(KnightRMSGUI.this, "Please enter search criteria.");
//            }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
//
//    KnightEDU.DBMS.Query.Course courseQuery = db.queryCourse();
//
//    KnightEDU.DBMS.Query.CourseID.PNS courseIDQuery = (KnightEDU.DBMS.Query.CourseID.PNS)courseQuery.specifyCourseID();
//
//    if (hasPrefix())
//        courseIDQuery = courseIDQuery.containsPrefix(prefixField.getText());
//    if (hasNumber())
//        courseIDQuery = courseIDQuery.containsNumberEqualTo(numberField.getText());
//    if (hasSuffix())
//        courseIDQuery = courseIDQuery.containsSuffix(suffixField.getText());
//
//    courseQuery = courseIDQuery.build();
//
//    if (hasName())
//        courseQuery = courseQuery.nameContains(nameField.getText());
//
//    // more code
//
//    Set<KnightEDU.Course> results = courseQuery.invoke();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void gradePrefBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradePrefBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradePrefBox1ActionPerformed

    private void prefixFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_prefixFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel courseInfoTopPan;
    private javax.swing.JList courseList;
    private javax.swing.JScrollPane courseListScrollPane;
    private javax.swing.JPanel courseNamePan1;
    private javax.swing.JLabel courseNumLab;
    private javax.swing.JPanel courseOptionsInsidePan;
    private javax.swing.JPanel courseOptionsPan;
    private javax.swing.JPanel coursePlannerLeftPan;
    private javax.swing.JPanel coursePlannerRightPan;
    private javax.swing.JSeparator coursePlannerSeparator;
    private javax.swing.JLabel coursePrefixLab2;
    private javax.swing.JPanel courseSearchPan;
    private javax.swing.JLabel courseSuffixLab;
    private javax.swing.JLabel creditsMaxLab2;
    private javax.swing.JLabel creditsMinLab2;
    private javax.swing.JPanel creditsPan2;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JCheckBox fallEvenBox;
    private javax.swing.JLabel fallLab;
    private javax.swing.JCheckBox fallOddBox;
    private javax.swing.JComboBox gradePrefBox1;
    private javax.swing.JPanel gradePrefPan1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField maxCreditsField;
    private javax.swing.JTextField minCreditsField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField numberField;
    private javax.swing.JCheckBox occasionalBox;
    private javax.swing.JTextField prefixField;
    private KnightRMS.PrerequisitesPanel prerequisitesPanel1;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel semOfferedPan;
    private javax.swing.JPanel semOfferedSemPan;
    private javax.swing.JSeparator semOfferedSeparator;
    private javax.swing.JCheckBox springEvenBox;
    private javax.swing.JLabel springLab;
    private javax.swing.JCheckBox springOddBox;
    private javax.swing.JTextField suffixField;
    private javax.swing.JCheckBox summerEvenBox;
    private javax.swing.JLabel summerLab;
    private javax.swing.JCheckBox summerOddBox;
    // End of variables declaration//GEN-END:variables


        public boolean hasCompleteCourseID()
    {
        if (prefixField.getText() != null && numberField.getText() != null && suffixField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasPartialCourseID()
    {
        if (nameField.getText() != null || numberField.getText() != null || suffixField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasPrefix()
    {
        if (prefixField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasNumber()
    {
        if (numberField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasSuffix()
    {
        if (suffixField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasName()
    {
        if (nameField.getText() != null)
            return true;
        else
            return false;
    }

    public boolean hasDescription()
    {
        if (descriptionArea.getText() != null)
            return true;
        else
            return false;
    }
}
