package knightrms;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KnightsSampleGUI.java
 *
 * Created on Feb 5, 2011, 10:23:33 PM
 */

/**
 *
 * @author Evan
 */

public class KnightRegManSysGUI extends javax.swing.JFrame {

    /** Creates new form KnightsSampleGUI */
    public KnightRegManSysGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        coursePlannerTab = new javax.swing.JTabbedPane();
        coursePlannerPan = new javax.swing.JPanel();
        coursePlannerLeftPan = new javax.swing.JPanel();
        courseInfoLab = new javax.swing.JLabel();
        courseInfoTopPan = new javax.swing.JPanel();
        courseInfoLabelPan = new javax.swing.JPanel();
        courseIDLab = new javax.swing.JLabel();
        courseNameLab = new javax.swing.JLabel();
        courseDescipLab = new javax.swing.JLabel();
        creditsLab = new javax.swing.JLabel();
        gradingPrefLab = new javax.swing.JLabel();
        courseInfoInputPan = new javax.swing.JPanel();
        courseIDInsidePan = new javax.swing.JPanel();
        coursePrefixLab = new javax.swing.JLabel();
        coursePrefix = new javax.swing.JTextField();
        courseNumLab = new javax.swing.JLabel();
        courseNum = new javax.swing.JTextField();
        courseSuffixLab = new javax.swing.JLabel();
        courseSuffix = new javax.swing.JTextField();
        courseName = new javax.swing.JTextField();
        courseDescrip = new javax.swing.JTextField();
        courseCreditsPan = new javax.swing.JPanel();
        creditsMinLab = new javax.swing.JLabel();
        creditsMin = new javax.swing.JTextField();
        creditsMaxLab = new javax.swing.JLabel();
        creditsMax = new javax.swing.JTextField();
        gradePrefComboBox = new javax.swing.JComboBox();
        PrereqsPan = new javax.swing.JPanel();
        prereqsLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        editPrereqsBut = new javax.swing.JButton();
        coursePlannerSep = new javax.swing.JSeparator();
        coursePlannerRightPan = new javax.swing.JPanel();
        semOfferedPan = new javax.swing.JPanel();
        semestersOfferedLab = new javax.swing.JLabel();
        semOfferedAllBoxPan = new javax.swing.JPanel();
        occasionalBox = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        semOfferedSemPan = new javax.swing.JPanel();
        fallLab = new javax.swing.JLabel();
        fallEvenBox = new javax.swing.JCheckBox();
        fallOddBox = new javax.swing.JCheckBox();
        springLab = new javax.swing.JLabel();
        springEvenBox = new javax.swing.JCheckBox();
        springOddBox = new javax.swing.JCheckBox();
        summerLab = new javax.swing.JLabel();
        summerEvenBox = new javax.swing.JCheckBox();
        summerOddBox = new javax.swing.JCheckBox();
        courseSearchPan = new javax.swing.JPanel();
        courseSearchResultsLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        courseOptionsPan = new javax.swing.JPanel();
        courseOptionsLab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        courseOptionsInsidePan = new javax.swing.JPanel();
        saveCourseBut = new javax.swing.JButton();
        removeCourseBut = new javax.swing.JButton();
        knightRMSMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Knight Registrar Management System");

        coursePlannerTab.setBackground(new java.awt.Color(255, 255, 102));

        coursePlannerPan.setLayout(new javax.swing.BoxLayout(coursePlannerPan, javax.swing.BoxLayout.X_AXIS));

        coursePlannerLeftPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseInfoLab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        courseInfoLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseInfoLab.setText("Course Information");
        coursePlannerLeftPan.add(courseInfoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        courseInfoTopPan.setLayout(new javax.swing.BoxLayout(courseInfoTopPan, javax.swing.BoxLayout.LINE_AXIS));

        courseInfoLabelPan.setLayout(new java.awt.GridLayout(5, 1));

        courseIDLab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        courseIDLab.setText("Course ID:");
        courseIDLab.setIconTextGap(5);
        courseIDLab.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        courseInfoLabelPan.add(courseIDLab);

        courseNameLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        courseNameLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseNameLab.setText("Course Name:");
        courseInfoLabelPan.add(courseNameLab);

        courseDescipLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        courseDescipLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseDescipLab.setText("Course Description:");
        courseInfoLabelPan.add(courseDescipLab);

        creditsLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        creditsLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        creditsLab.setText("Credits:");
        courseInfoLabelPan.add(creditsLab);

        gradingPrefLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        gradingPrefLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gradingPrefLab.setText("Grading Preference:");
        courseInfoLabelPan.add(gradingPrefLab);

        courseInfoTopPan.add(courseInfoLabelPan);

        courseInfoInputPan.setLayout(new java.awt.GridLayout(5, 1));

        courseIDInsidePan.setAlignmentX(0.0F);
        courseIDInsidePan.setAlignmentY(0.0F);
        courseIDInsidePan.setLayout(new java.awt.GridLayout(1, 6));

        coursePrefixLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        coursePrefixLab.setText("Prefix: ");
        courseIDInsidePan.add(coursePrefixLab);
        courseIDInsidePan.add(coursePrefix);

        courseNumLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        courseNumLab.setText(" Number: ");
        courseIDInsidePan.add(courseNumLab);
        courseIDInsidePan.add(courseNum);

        courseSuffixLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        courseSuffixLab.setText(" Suffix: ");
        courseIDInsidePan.add(courseSuffixLab);
        courseIDInsidePan.add(courseSuffix);

        courseInfoInputPan.add(courseIDInsidePan);
        courseInfoInputPan.add(courseName);
        courseInfoInputPan.add(courseDescrip);

        courseCreditsPan.setLayout(new java.awt.GridLayout());

        creditsMinLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        creditsMinLab.setText("Min: ");
        courseCreditsPan.add(creditsMinLab);
        courseCreditsPan.add(creditsMin);

        creditsMaxLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        creditsMaxLab.setText("Max: ");
        courseCreditsPan.add(creditsMaxLab);
        courseCreditsPan.add(creditsMax);

        courseInfoInputPan.add(courseCreditsPan);

        gradePrefComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Letter", "S / U" }));
        gradePrefComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradePrefComboBoxActionPerformed(evt);
            }
        });
        courseInfoInputPan.add(gradePrefComboBox);

        courseInfoTopPan.add(courseInfoInputPan);

        coursePlannerLeftPan.add(courseInfoTopPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 100));

        PrereqsPan.setLayout(new java.awt.GridBagLayout());

        prereqsLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        prereqsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prereqsLab.setText("Prerequisites:");
        PrereqsPan.add(prereqsLab, new java.awt.GridBagConstraints());

        jList6.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane2.setViewportView(jList6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        PrereqsPan.add(jScrollPane2, gridBagConstraints);

        editPrereqsBut.setText("Edit Prerequisites");
        editPrereqsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPrereqsButActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 11, 0);
        PrereqsPan.add(editPrereqsBut, gridBagConstraints);

        coursePlannerLeftPan.add(PrereqsPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 200));

        coursePlannerPan.add(coursePlannerLeftPan);

        coursePlannerSep.setOrientation(javax.swing.SwingConstants.VERTICAL);
        coursePlannerPan.add(coursePlannerSep);

        coursePlannerRightPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        semOfferedPan.setLayout(new java.awt.GridBagLayout());

        semestersOfferedLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        semestersOfferedLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semestersOfferedLab.setText("Semesters Offered:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        semOfferedPan.add(semestersOfferedLab, gridBagConstraints);

        semOfferedAllBoxPan.setLayout(new javax.swing.BoxLayout(semOfferedAllBoxPan, javax.swing.BoxLayout.LINE_AXIS));

        occasionalBox.setText("Occasional");
        occasionalBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        occasionalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occasionalBoxActionPerformed(evt);
            }
        });
        semOfferedAllBoxPan.add(occasionalBox);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        semOfferedAllBoxPan.add(jSeparator7);

        semOfferedSemPan.setLayout(new java.awt.GridLayout(3, 3, 40, 20));

        fallLab.setFont(new java.awt.Font("Tahoma", 1, 11));
        fallLab.setText("     Fall:");
        semOfferedSemPan.add(fallLab);

        fallEvenBox.setText("Even");
        fallEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(fallEvenBox);

        fallOddBox.setText("Odd");
        fallOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fallOddBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fallOddBoxActionPerformed(evt);
            }
        });
        semOfferedSemPan.add(fallOddBox);

        springLab.setFont(new java.awt.Font("Tahoma", 1, 11));
        springLab.setText("     Spring:");
        semOfferedSemPan.add(springLab);

        springEvenBox.setText("Even");
        springEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        springEvenBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                springEvenBoxActionPerformed(evt);
            }
        });
        semOfferedSemPan.add(springEvenBox);

        springOddBox.setText("Odd");
        springOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(springOddBox);

        summerLab.setFont(new java.awt.Font("Tahoma", 1, 11));
        summerLab.setText("     Summer:");
        semOfferedSemPan.add(summerLab);

        summerEvenBox.setText("Even");
        summerEvenBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(summerEvenBox);

        summerOddBox.setText("Odd");
        summerOddBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        semOfferedSemPan.add(summerOddBox);

        semOfferedAllBoxPan.add(semOfferedSemPan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        semOfferedPan.add(semOfferedAllBoxPan, gridBagConstraints);

        coursePlannerRightPan.add(semOfferedPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 377, 175));

        courseSearchPan.setLayout(new java.awt.GridBagLayout());

        courseSearchResultsLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        courseSearchResultsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseSearchResultsLab.setText("Course Search Results");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        courseSearchPan.add(courseSearchResultsLab, gridBagConstraints);

        jList1.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        courseSearchPan.add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Search");
        courseSearchPan.add(jButton1, new java.awt.GridBagConstraints());

        coursePlannerRightPan.add(courseSearchPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        courseOptionsPan.setLayout(new java.awt.GridLayout(3, 1));

        courseOptionsLab.setFont(new java.awt.Font("Tahoma", 1, 12));
        courseOptionsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseOptionsLab.setText("Course Options");
        courseOptionsPan.add(courseOptionsLab);
        courseOptionsPan.add(jLabel3);

        courseOptionsInsidePan.setLayout(new java.awt.GridLayout(1, 2));

        saveCourseBut.setText("Save Course");
        courseOptionsInsidePan.add(saveCourseBut);

        removeCourseBut.setText("Remove Course");
        courseOptionsInsidePan.add(removeCourseBut);

        courseOptionsPan.add(courseOptionsInsidePan);

        coursePlannerRightPan.add(courseOptionsPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 391, -1, -1));

        coursePlannerPan.add(coursePlannerRightPan);

        coursePlannerTab.addTab("Course Planner", coursePlannerPan);

        fileMenu.setText("File");

        closeMenuItem.setText("Close");
        fileMenu.add(closeMenuItem);

        knightRMSMenuBar.add(fileMenu);

        setJMenuBar(knightRMSMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursePlannerTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursePlannerTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void springEvenBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_springEvenBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_springEvenBoxActionPerformed

    private void fallOddBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fallOddBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fallOddBoxActionPerformed

    private void editPrereqsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPrereqsButActionPerformed
        // TODO add your handling code here:
        new PrereqEdit(KnightRegManSysGUI.this, true).setVisible(true);
}//GEN-LAST:event_editPrereqsButActionPerformed

    private void gradePrefComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradePrefComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_gradePrefComboBoxActionPerformed

    private void occasionalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occasionalBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occasionalBoxActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnightRegManSysGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrereqsPan;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JPanel courseCreditsPan;
    private javax.swing.JLabel courseDescipLab;
    private javax.swing.JTextField courseDescrip;
    private javax.swing.JPanel courseIDInsidePan;
    private javax.swing.JLabel courseIDLab;
    private javax.swing.JPanel courseInfoInputPan;
    private javax.swing.JLabel courseInfoLab;
    private javax.swing.JPanel courseInfoLabelPan;
    private javax.swing.JPanel courseInfoTopPan;
    private javax.swing.JTextField courseName;
    private javax.swing.JLabel courseNameLab;
    private javax.swing.JTextField courseNum;
    private javax.swing.JLabel courseNumLab;
    private javax.swing.JPanel courseOptionsInsidePan;
    private javax.swing.JLabel courseOptionsLab;
    private javax.swing.JPanel courseOptionsPan;
    private javax.swing.JPanel coursePlannerLeftPan;
    private javax.swing.JPanel coursePlannerPan;
    private javax.swing.JPanel coursePlannerRightPan;
    private javax.swing.JSeparator coursePlannerSep;
    private javax.swing.JTabbedPane coursePlannerTab;
    private javax.swing.JTextField coursePrefix;
    private javax.swing.JLabel coursePrefixLab;
    private javax.swing.JPanel courseSearchPan;
    private javax.swing.JLabel courseSearchResultsLab;
    private javax.swing.JTextField courseSuffix;
    private javax.swing.JLabel courseSuffixLab;
    private javax.swing.JLabel creditsLab;
    private javax.swing.JTextField creditsMax;
    private javax.swing.JLabel creditsMaxLab;
    private javax.swing.JTextField creditsMin;
    private javax.swing.JLabel creditsMinLab;
    private javax.swing.JButton editPrereqsBut;
    private javax.swing.JCheckBox fallEvenBox;
    private javax.swing.JLabel fallLab;
    private javax.swing.JCheckBox fallOddBox;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox gradePrefComboBox;
    private javax.swing.JLabel gradingPrefLab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JMenuBar knightRMSMenuBar;
    private javax.swing.JCheckBox occasionalBox;
    private javax.swing.JLabel prereqsLab;
    private javax.swing.JButton removeCourseBut;
    private javax.swing.JButton saveCourseBut;
    private javax.swing.JPanel semOfferedAllBoxPan;
    private javax.swing.JPanel semOfferedPan;
    private javax.swing.JPanel semOfferedSemPan;
    private javax.swing.JLabel semestersOfferedLab;
    private javax.swing.JCheckBox springEvenBox;
    private javax.swing.JLabel springLab;
    private javax.swing.JCheckBox springOddBox;
    private javax.swing.JCheckBox summerEvenBox;
    private javax.swing.JLabel summerLab;
    private javax.swing.JCheckBox summerOddBox;
    // End of variables declaration//GEN-END:variables

}
