/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrerequisitesPanel.java
 *
 * Created on Apr 22, 2011, 4:22:26 PM
 */

package KnightRMS;

/**
 *
 * @author Evan
 */
public class PrerequisitesPanel extends javax.swing.JPanel {


    /** Creates new form PrerequisitesPanel */
    public PrerequisitesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prereqListScrollPane = new javax.swing.JScrollPane();
        prereqList = new javax.swing.JList();
        editPrereqsButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Prerequisites"));
        setMinimumSize(new java.awt.Dimension(200, 72));
        setPreferredSize(getMinimumSize());
        setLayout(new java.awt.BorderLayout());

        prereqList.setBackground(new java.awt.Color(204, 255, 255));
        prereqListScrollPane.setViewportView(prereqList);

        add(prereqListScrollPane, java.awt.BorderLayout.CENTER);

        editPrereqsButton.setText("Edit Prerequisites");
        editPrereqsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPrereqsButtonActionPerformed(evt);
            }
        });
        add(editPrereqsButton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void editPrereqsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPrereqsButtonActionPerformed
        // TODO add your handling code here:
        //new PrereqEdit(, true).setVisible(true);
        //        if (prefixField == null || numberField == null || suffixField == null) {
        //            JOptionPane.showMessageDialog(KnightRMSGUI.this, "Valid Course ID required");
        //            return;
        //        } else {
        //            new PrereqEdit(KnightRMSGUI.this, true).setVisible(true);
        //        }
        //             if (courseList.getSelectedValue() != null)
        //            {
        //                // open prerequisites window
        //                Course c = (Course) courseList.getSelectedValue();
        //
        //            }
        //            else
        //                JOptionPane.showMessageDialog(KnightRMSGUI.this, "No course is selected.");
}//GEN-LAST:event_editPrereqsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editPrereqsButton;
    private javax.swing.JList prereqList;
    private javax.swing.JScrollPane prereqListScrollPane;
    // End of variables declaration//GEN-END:variables

}
