/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SectionFinderGUI.java
 *
 * Created on Apr 23, 2011, 3:24:16 PM
 */

package knightrms;
import KnightEDU.DBMS.SQL.DB;
import KnightEDU.Days;
import KnightEDU.Section;
import java.util.Set;
import javax.swing.*;
/**
 *
 * @author CORY
 */
public class SectionFinderGUI extends javax.swing.JDialog {

    private KnightEDU.DBMS.SQL.Query.Section sectionQuery;
    private KnightEDU.Section r_val = null;


    public static KnightEDU.Section showDialog(java.awt.Frame parent, boolean modal, KnightEDU.DBMS.SQL.Query.Section sectionQuery)
    {
        SectionFinderGUI dialog = new SectionFinderGUI(parent, modal, sectionQuery);
        dialog.setVisible(true);
        return dialog.getSection();
        
    }

    private KnightEDU.Section getSection()
    {
        return r_val;
    }

    public SectionFinderGUI(java.awt.Frame parent, boolean modal, KnightEDU.DBMS.SQL.Query.Section sectionQuery) {
        super(parent, modal);
        initComponents();
        this.sectionQuery = sectionQuery;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        DaysComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        startTimeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        endTimeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buildingField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roomField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        selectedSectionIDField = new javax.swing.JTextField();
        selectedSectionIDLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sectionList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        DaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "U", "M", "T", "W", "R", "F", "S", "MW", "MWF", "TR", "TBA" }));
        DaysComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DaysComboBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(DaysComboBox, gridBagConstraints);

        jLabel2.setText("Days:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        startTimeField.setColumns(4);
        startTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeFieldActionPerformed(evt);
            }
        });
        startTimeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                startTimeFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(startTimeField, gridBagConstraints);

        jLabel3.setText("(Military) Start Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel3, gridBagConstraints);

        endTimeField.setColumns(4);
        endTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimeFieldActionPerformed(evt);
            }
        });
        endTimeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                endTimeFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(endTimeField, gridBagConstraints);

        jLabel4.setText("(Military) End Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        buildingField.setColumns(10);
        buildingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingFieldActionPerformed(evt);
            }
        });
        buildingField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                buildingFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(buildingField, gridBagConstraints);

        jLabel5.setText("Building:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel5, gridBagConstraints);

        roomField.setColumns(10);
        roomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomFieldActionPerformed(evt);
            }
        });
        roomField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                roomFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(roomField, gridBagConstraints);

        jLabel6.setText("Room:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel6, gridBagConstraints);

        selectedSectionIDField.setColumns(25);
        selectedSectionIDField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(selectedSectionIDField, gridBagConstraints);

        selectedSectionIDLabel.setText("Section:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(selectedSectionIDLabel, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        jPanel2.add(OKButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        jPanel4.add(jPanel2);

        getContentPane().add(jPanel4);

        sectionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sectionListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(sectionList);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeFieldActionPerformed
        updateSearchListing();
      

        
}//GEN-LAST:event_endTimeFieldActionPerformed

    private void roomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomFieldActionPerformed
        updateSearchListing();
}//GEN-LAST:event_roomFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        r_val = null;
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void startTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeFieldActionPerformed
        updateSearchListing();
    }//GEN-LAST:event_startTimeFieldActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OKButtonActionPerformed
    {//GEN-HEADEREND:event_OKButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    private void updateSearchListing()
    {
        // Waiting on Alex to implement in database
        //KnightEDU.DMBS.Query.Section sectionQuery = db.querySection().
        //Search code to populate the section list in the Section finder dialog box

        sectionQuery.reset();
        if (!startTimeField.getText().isEmpty())
            sectionQuery = sectionQuery.startTime(Integer.parseInt(startTimeField.getText()));
        if (!endTimeField.getText().isEmpty())
            sectionQuery = sectionQuery.endTime(Integer.parseInt(endTimeField.getText()));

        if(hasBuilding()){
            sectionQuery = sectionQuery.specifyBuilding(buildingField.getText());
        }
        if(hasRoom()){
            sectionQuery = sectionQuery.specifyRoom(roomField.getText());
        }

        if (!((String)DaysComboBox.getSelectedItem()).isEmpty())
            sectionQuery = sectionQuery.specifyDays(Days.valueOf((String)DaysComboBox.getSelectedItem()));

        Set<Section> results = sectionQuery.invoke();

        //sectionList.setListData(qSection.toArray());

        DefaultListModel searchResultsListData = new DefaultListModel();
        for (KnightEDU.Section i : results)
        {
            searchResultsListData.addElement(i);
        }
        sectionList.setModel(searchResultsListData);
    }

    private void sectionListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_sectionListValueChanged
    {//GEN-HEADEREND:event_sectionListValueChanged
        if (sectionList.getSelectedValue() == null) return;
        r_val = (KnightEDU.Section)sectionList.getSelectedValue();
        selectedSectionIDField.setText(r_val.toString());
    }//GEN-LAST:event_sectionListValueChanged

    private void roomFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_roomFieldFocusLost
    {//GEN-HEADEREND:event_roomFieldFocusLost
        updateSearchListing();
    }//GEN-LAST:event_roomFieldFocusLost

    private void buildingFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buildingFieldFocusLost
    {//GEN-HEADEREND:event_buildingFieldFocusLost
       updateSearchListing();
    }//GEN-LAST:event_buildingFieldFocusLost

    private void buildingFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buildingFieldActionPerformed
    {//GEN-HEADEREND:event_buildingFieldActionPerformed
        updateSearchListing();
    }//GEN-LAST:event_buildingFieldActionPerformed

    private void endTimeFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_endTimeFieldFocusLost
    {//GEN-HEADEREND:event_endTimeFieldFocusLost
        updateSearchListing();
    }//GEN-LAST:event_endTimeFieldFocusLost

    private void startTimeFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_startTimeFieldFocusLost
    {//GEN-HEADEREND:event_startTimeFieldFocusLost
       updateSearchListing();
    }//GEN-LAST:event_startTimeFieldFocusLost

    private void DaysComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_DaysComboBoxItemStateChanged
    {//GEN-HEADEREND:event_DaysComboBoxItemStateChanged
        updateSearchListing();
    }//GEN-LAST:event_DaysComboBoxItemStateChanged



    private boolean hasBuilding(){
        return !buildingField.getText().isEmpty();
    }
    private boolean hasRoom(){
        return !roomField.getText().isEmpty();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DaysComboBox;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField buildingField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField endTimeField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roomField;
    private javax.swing.JList sectionList;
    private javax.swing.JTextField selectedSectionIDField;
    private javax.swing.JLabel selectedSectionIDLabel;
    private javax.swing.JTextField startTimeField;
    // End of variables declaration//GEN-END:variables

}
